Update install_theos

diff --git a/install_theos b/install_theos
--- a/install_theos
+++ b/install_theos
@@ -1,4 +1,43 @@
 #! /bin/bash
+
+#================================================
+#Part of uptime2 
+#Used for nothing just show can be removed.
+B='\033[0;30m'            #Black
+LR='\033[1;31m'           #Red 
+LG='\033[1;32m'           #Green
+P='\033[0;35m'            #Purple 
+NC='\033[0m'              #Default shell colour
+
+iosv="$(sw_vers -productVersion)"
+
+jbd=/taurine
+if test -d "$jbd"; then
+jb=$(tput setaf 5;)"Taurine"
+else
+jbd=/odyssey
+if test -d "$jbd";then  
+jb="${P}Odyssey" 
+else
+jbd=/.installed_odyssey
+if test -f "$jbd"; then  
+jb="$(tput setab 0;)${P}Odysseyra1n" 
+else
+jbd=/.installed_unc0ver
+if test -f "$jbd"; then  
+jb="${B}$(tput setab 7;)unc0ver"
+else
+jbd=/.bootstrapped
+if test -f "$jbd"; then
+jb="$(tput setaf 7;)$(tput setab 0;)checkra1n"
+else
+jb="${LR}Unknown Jailbreak?"
+fi fi  
+fi fi
+ fi 
+   
+#================================================
+
 procursus=(/.procursus_strapped)
 deb1=(420tools.deb) deb1down=(https://turannul.github.io/home/420tools.deb)
 deb2=(tai-depends-other.deb) deb2down=(https://turannul.github.io/home/tai-depends-other.deb)
@@ -23,59 +62,69 @@ cat << EOF
  ___           _        _ _           
 |_ _|_ __  ___| |_ __ _| | | ___ _ __ 
  | ||  _ \/ __| __/ _  | | |/ _ \  __|
- | || | | \__ \ || (_| | | |  __/ |   
+ | || | | \__ \ || (_| | | |  __/ |   x
 |___|_| |_|___/\__\__ _|_|_|\___|_|                                        
 
 EOF
-
-                   
-                   
-                   
-                   echo "I recommend connecting to Wi-Fi before proceeding."
-                   sleep 10 #give some time connect to Wi-Fi or option to stop?
-                   
-                    echo "Checking for wget..."
+                   echo "I suggest you connect to Wi-Fi network before proceeding."
+                   sleep 3
+echo ""
+                   echo "Hey seriously, if you don't want mobile data (Less than 500MB) to be used."
+                   sleep 15 #give some time connect to Wi-Fi or option to stop? 
+                   #I didn't find a way to determine connection type using bash. if someone knows how to-do please tell me.
+echo ""
+echo ""
+                   #================================================
+                   echo "iOS Version: $iosv"
+                   echo "Jailbreak: $jb"
+                   (tput setab 0)
+                   (tput setaf 2)
+                   #================================================
+echo ""
+echo ""
+                   echo "Checking for wget..."
                    if test ! "$(which wget)"; then
-                   echo "wget is not found, installing now."
+                   echo "wget is not found, Installing now..."
                    apt install wget -y
                    fi
-                   
-                    echo "Checking for deb files..."
+echo ""
+                   echo "Checking for deb files..."
                    if [ ! -f "$deb1" ]; then
-                   echo "$deb1 was not found, downloading..."
+                   echo "$deb1 was not found, Downloading..."
                    wget -q --show-progress $deb1down
                    if [ ! -f "$deb4" ]; then
-                   echo "$deb4 was not found, downloading..."
+                   echo "$deb4 was not found, Downloading..."
                    wget -q --show-progress $deb4down
 
-
+echo ""
+echo ""
                    if test -f "$procursus" ; then
                    echo $(tput setaf 190)"Should install from Procursus" $(tput setaf 2)
                    if [ ! -f "$deb3" ]; then
-                   echo "$deb3 was not found, downloading..."
+                   echo "$deb3 was not found, Downloading..."
                    wget -q --show-progress $deb3down 
                    dpkg -i 420tools.deb tai-depends-procursus.deb tai.deb
-                   apt --fix-broken install -y --allow-unauthenticated
-                   #Quick note dpkg -i does not install depends with so apt is required.
-                   else		
+                   # gap /usr/bin/dpkg -i 420tools.deb tai-depends-procursus.deb tai.deb
+
+                   else 
+
                    echo $(tput setaf 190)"Should install from Bingner" $(tput setaf 2)
                    if [ ! -f "$deb2" ]; then
-                   echo "$deb2 was not found, downloading..."
+                   echo "$deb2 was not found, Downloading..."
                    wget -q --show-progress $deb2down 
                    dpkg -i 420tools.deb tai-depends-other.deb tai.deb
+                   # gap /usr/bin/dpkg -i 420tools.deb tai-depends-other.deb tai.deb
+                   fi   fi
+                    fi fi 
+                     fi   #I love doing this                      
+
+echo ""
+                   #To install depends.
                    apt --fix-broken install -y --allow-unauthenticated
-                   #Quick note dpkg -i does not install depends with so apt is required.
-                   fi
-                     fi
-                       fi
-                         fi
-                           fi #I love doing this
-                           
-                   # In case if you embed script in preferences. gap /usr/bin/dpkg -i 420tools.deb tai-depends-other.deb tai.deb & dpkg -i 420tools.deb tai-depends-procursus.deb tai.deb cam be used with.
+                   dpkg --configure -a
+                   #Just to make sure everything is configured.
                    echo "Cleaning up..."
-                   dpkg --configure -a 
-                   #Just to make sure everything is okay.
                    rm $deb1 $deb2 $deb3 $deb4 >/dev/null 2>&1
                    killall Preferences >/dev/null 2>&1 #Reload settings to appear preferences.
-                   echo "We are done here."
+                   echo "We are done."
                    exit 0
